In [1]:
import numpy as np
import pandas as pd
import math

In [2]:
lead_concentrations = np.array([6.7, 5.4, 5.2, 6.0, 8.7,
                       6.0, 6.4, 8.3, 5.3, 5.9,
                       7.6, 5.0, 6.9, 6.8, 4.9,
                       6.3, 5.0, 6.0, 7.2, 8.0, 
                       8.1, 7.2, 10.9, 9.2, 8.6,
                       6.2, 6.1, 14.1, 10.6, 8.4])
lead_concentrations

array([ 6.7,  5.4,  5.2,  6. ,  8.7,  6. ,  6.4,  8.3,  5.3,  5.9,  7.6,
        5. ,  6.9,  6.8,  4.9,  6.3,  5. ,  6. ,  7.2,  8. ,  8.1,  7.2,
       10.9,  9.2,  8.6,  6.2,  6.1, 14.1, 10.6,  8.4])

In [3]:
lead_mean=np.mean(lead_concentrations)
lead_mean

7.2333333333333325

In [4]:
lead_std=np.std(lead_concentrations,ddof=1)
lead_std

2.0450669550346543

In [5]:
lead_var=np.var(lead_concentrations,ddof=1)
lead_var

4.182298850574712

In [6]:
a=lead_mean+lead_std

In [7]:
b=lead_mean-lead_std

In [8]:
within_one_std=lead_concentrations[(lead_concentrations<=a) & (lead_concentrations>=b)]
within_one_std.size

24

In [9]:
a_2=lead_mean+2*lead_std
b_2=lead_mean-2*lead_std

In [10]:
within_two_std=lead_concentrations[(lead_concentrations<=a_2) & (lead_concentrations>=b_2)]
within_two_std.size

29

In [11]:
pi_25=np.percentile(lead_concentrations,25)
pi_25

6.0

In [12]:
pi_75=np.percentile(lead_concentrations,75)
pi_75

8.25

In [13]:
IQR=pi_75-pi_25
IQR

2.25

In [14]:
pi_10=np.percentile(lead_concentrations,10)
pi_10

5.180000000000001

In [15]:
pi_90=np.percentile(lead_concentrations,90)
pi_90

9.340000000000002

In [16]:
suspected_outliers=lead_concentrations[(lead_concentrations<=pi_25-1.5*IQR) | (lead_concentrations>=pi_75+1.5*IQR)]
suspected_outliers

array([14.1])

In [17]:
prob_seventh_order_stat=math.comb(8,7)*(0.7)**7*(0.3)+math.comb(8,8)*(0.7)**8
prob_seventh_order_stat

0.2552983299999999

In [18]:
prob_seventh_order_stat_2=math.comb(8,7)*(0.7)**7*(0.3)+math.comb(8,6)*(0.7)**6*(0.3)**2+math.comb(8,5)*(0.7)**5*(0.3)**3
prob_seventh_order_stat_2

0.7482476399999998

In [20]:
np.sort(lead_concentrations)

array([ 4.9,  5. ,  5. ,  5.2,  5.3,  5.4,  5.9,  6. ,  6. ,  6. ,  6.1,
        6.2,  6.3,  6.4,  6.7,  6.8,  6.9,  7.2,  7.2,  7.6,  8. ,  8.1,
        8.3,  8.4,  8.6,  8.7,  9.2, 10.6, 10.9, 14.1])