In [1]:
import numpy as np
from numpy import linalg

In [2]:
D=np.diag([10,10,8,5])

In [5]:
L=np.diag([-5,4,1],k=-1)

In [6]:
U=np.diag([-5,4,1],k=1)

In [10]:
b=np.array([6,25,-11,-11])

In [ ]:
x_0=np.array([[0,0,0,0]]).transpose()

In [17]:
GS_2 = lambda x,D,L,U,b: linalg.inv(D-L)*(U)+linalg.inv(D-L)*b

In [169]:
def Jacobi(x_0,D,L,U,b,n=100,tol=1e-6):
    A=D-L-U
    G_j=np.matmul(linalg.inv(D),L+U)
    c_j=np.matmul(linalg.inv(D),b)
    x=x_0
    for i in np.arange(n):
        x_0=np.matmul(G_j,x_0)+c_j
        x=np.append(x,x_0,axis=1)
        if linalg.norm(np.matmul(A,x_0)-b,np.inf)<tol:
            return x_0,linalg.norm(np.matmul(A,x_0)-b,np.inf),i
    return x,x_0

In [170]:
def GS(x_0,D,L,U,b,n=100,tol=1e-6):
    A=D-L-U
    G_g=np.matmul(linalg.inv(D-L),U)
    c_g=np.matmul(linalg.inv(D-L),b)
    x=x_0
    for i in np.arange(n):
        x_0=np.matmul(G_g,x_0)+c_g
        x=np.append(x,x_0,axis=1)
        if linalg.norm(np.matmul(A,x_0)-b)<tol:
            return x_0,linalg.norm(np.matmul(A,x_0)-b,np.inf),i
    return x

In [171]:
Jacobi(x_0,D,L,U,b)

(array([[-0.79764695],
        [ 2.79529409],
        [-0.25882365],
        [-2.25176471]]),
 9.688194344548151e-07,
 42)

In [172]:
GS(x_0,D,L,U,b)

(array([[-0.79764691],
        [ 2.79529398],
        [-0.2588236 ],
        [-2.25176472]]),
 7.967884450010843e-07,
 19)

In [175]:
B=np.array([[1,1,2,3],
            [4,4,5,7],
            [6,3,2,1],
            [9,8,7,6]])

In [182]:
ind=np.diag_indices_from(B)

In [193]:
def LDU(A):
    D=np.diag(np.diagonal(A))
    L=-1*(np.tril(A)-D)
    U=-1*(np.triu(A)-D)
    print(D,L,U)

In [7]:
np.matmul(linalg.inv(D),U+L)

array([[ 0.   , -0.5  ,  0.   ,  0.   ],
       [-0.5  ,  0.   ,  0.4  ,  0.   ],
       [ 0.   ,  0.5  ,  0.   ,  0.125],
       [ 0.   ,  0.   ,  0.2  ,  0.   ]])

In [11]:
linalg.inv(D).dot(b)

array([ 0.6  ,  2.5  , -1.375, -2.2  ])

In [14]:
0.6-5/4

-0.65

In [13]:
5/4

1.25

In [16]:
2.5-0.3-11/8*2/5

1.6500000000000001

In [17]:
-99/40

-2.475

In [20]:
np.matmul(linalg.inv(D-L),U)

array([[ 0.   , -0.5  ,  0.   ,  0.   ],
       [ 0.   ,  0.25 ,  0.4  ,  0.   ],
       [ 0.   ,  0.125,  0.2  ,  0.125],
       [ 0.   ,  0.025,  0.04 ,  0.025]])

In [23]:
linalg.inv(D-L).dot(b)

array([ 0.6  ,  2.2  , -0.275, -2.255])

In [33]:
-2.255*200

-451.0

In [34]:
-451/200

-2.255

In [35]:
11/4-11/100

2.64

In [41]:
40*200

8000

In [42]:
41*451

18491

In [38]:
11*40-16*33-451

-539

In [39]:
-539/1600

-0.336875

In [43]:
11/200-11/1000-18491/8000

-2.267375

In [44]:
11*40-11*8-18491

-18139