In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from numpy.linalg import eig

In [17]:
L=np.array([[0,3,1.5],
            [1,0,0],
            [0,1,0.5]])


In [18]:
w,v=eig(L)
print('E-value',w)
print('E-vector',v)

E-value [ 2.00000000e+00 -1.50000000e+00  3.65215817e-17]
E-vector [[-8.57142857e-01  8.01783726e-01 -6.60989847e-16]
 [-4.28571429e-01 -5.34522484e-01 -4.47213595e-01]
 [-2.85714286e-01  2.67261242e-01  8.94427191e-01]]


In [40]:
def N_k(N_0,L,k):
    for i in np.arange(k):
        N_0=np.matmul(L,N_0)
    return N_0

In [45]:
def N_k_2(N_0,L,k):
    e_val,e_vec=eig(L)
    a=np.linalg.solve(e_vec,N_0)
    return a[0]*(e_val[0]**k)*e_vec[0]+a[1]*(e_val[1]**k)*e_vec[1]+a[2]*(e_val[2]**k)*e_vec[2]
    

In [43]:
N_0=np.array([30,10,10])
N_0

array([30, 10, 10])

In [44]:
np.linalg.solve(v,N_0)

array([-3.00000000e+01,  5.34522484e+00, -4.63553981e-15])

In [41]:
n_k=N_k(N_0,L,10)

In [47]:
n_k_2=N_k_2(N_0,L,10)
n_k_2

array([ 26199.3288861 , -24795.55330911,   -137.84580889])

In [42]:
n_k

array([[26578.56445312],
       [13000.95703125],
       [ 8859.52148438]])

In [32]:
n_0_prop=n_k[3][1][0]/(np.sum(n_k[3][1]))
n_0_prop

0.30388509326645446