In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from numpy.linalg import eig

In [78]:
b=np.array([0.000,0.045,0.391,0.472,0.484,0.546,0.543,0.502,0.468,0.459,0.433,0.421])
S=np.array([0.845,0.975,0.965,0.950,0.926,0.895,0.850,0.786,0.691,0.561,0.370])
L=np.zeros((12,12))
L[0]=b
for i in np.arange(1,12):
    L[i][i-1]=S[i-1]

In [80]:
L

array([[0.   , 0.045, 0.391, 0.472, 0.484, 0.546, 0.543, 0.502, 0.468,
        0.459, 0.433, 0.421],
       [0.845, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   ],
       [0.   , 0.975, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.965, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.95 , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.926, 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.895, 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.85 , 0.   , 0.   ,
        0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.786, 0.   ,
        0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.691,
        0.   , 0.   

In [65]:
e_value,e_vector=eig(L)

In [73]:
e_value

array([ 1.17557142+0.j        ,  0.56162493+0.54934695j,
        0.56162493-0.54934695j,  0.23526738+0.6945441j ,
        0.23526738-0.6945441j , -0.1301436 +0.71474201j,
       -0.1301436 -0.71474201j, -0.35689924+0.56111754j,
       -0.35689924-0.56111754j, -0.6585493 +0.j        ,
       -0.56836052+0.31311574j, -0.56836052-0.31311574j])

In [66]:
e_value[0]

(1.1755714232604326+0j)

In [70]:
N_0=np.array([np.zeros(12)]).transpose()
N_0[4][0]=1000
N_0
def N_k(N_0,L,k):
    e_val,e_vec=eig(L)
    e_vec_i=np.linalg.inv(e_vec)
    lambda_1=np.identity(12)
    for i in np.arange(12):
        lambda_1[i][i]=e_val[i]**k
    N_0=np.matmul(e_vec_i,N_0)
    N_0=np.matmul(lambda_1,N_0)
    
    return np.matmul(e_vec,N_0)

In [71]:
N_k(N_0,L,100)

<ipython-input-70-0d3dc43db484>:9: ComplexWarning: Casting complex values to real discards the imaginary part
  lambda_1[i][i]=e_val[i]**k


array([[2.90878198e+09-1.41456535e-06j],
       [2.09083066e+09-1.01678868e-06j],
       [1.73410126e+09-8.43308154e-07j],
       [1.42348452e+09-6.92252595e-07j],
       [1.15034294e+09-5.59421531e-07j],
       [9.06127474e+08-4.40657477e-07j],
       [6.89863732e+08-3.35486585e-07j],
       [4.98807780e+08-2.42574455e-07j],
       [3.33508375e+08-1.62187952e-07j],
       [1.96035973e+08-9.53339565e-08j],
       [9.35512538e+07-4.54947683e-08j],
       [2.94443734e+07-1.43190486e-08j]])

In [62]:
e_vector.transpose()[0]

array([0.63635094+0.j, 0.45740866+0.j, 0.37936737+0.j, 0.3114141 +0.j,
       0.25165922+0.j, 0.19823248+0.j, 0.15092071+0.j, 0.10912361+0.j,
       0.07296125+0.j, 0.04288657+0.j, 0.0204661 +0.j, 0.00644151+0.j])

In [74]:
pop_prop=e_vector.transpose()[0]/sum(e_vector.transpose()[0])
pop_prop

array([0.24129497+0.j, 0.17344267+0.j, 0.14385056+0.j, 0.11808367+0.j,
       0.0954255 +0.j, 0.07516686+0.j, 0.05722693+0.j, 0.04137808+0.j,
       0.02766584+0.j, 0.01626196+0.j, 0.00776045+0.j, 0.00244253+0.j])