In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from numpy.linalg import eig

In [3]:
L=np.array([[0,3,1.5],
            [1,0,0],
            [0,1,0.5]])


In [98]:
e_val,e_vec=eig(L)

In [100]:
np.round(e_vec,2)

array([[-0.86,  0.8 , -0.  ],
       [-0.43, -0.53, -0.45],
       [-0.29,  0.27,  0.89]])

In [102]:
np.round(np.linalg.inv(e_vec))

array([[-0., -1., -1.],
       [ 1., -1., -1.],
       [-0.,  0.,  1.]])

In [101]:
lambda_1=np.identity(3)
for i in np.arange(3):
    lambda_1[i][i]=e_val[i]
np.round(lambda_1,2)

array([[ 2. ,  0. ,  0. ],
       [ 0. , -1.5,  0. ],
       [ 0. ,  0. ,  0. ]])

In [81]:
N_0=np.array([[30,10,10]]).transpose()

In [96]:
def N_k(N_0,L,k):
    e_val,e_vec=eig(L)
    e_vec_i=np.linalg.inv(e_vec)
    lambda_1=np.identity(3)
    for i in np.arange(3):
        lambda_1[i][i]=e_val[i]**k
    N_0=np.matmul(e_vec_i,N_0)
    N_0=np.matmul(lambda_1,N_0)
    
    return np.matmul(e_vec,N_0)

In [97]:
N_k(N_0,L,1)

array([[45.],
       [30.],
       [15.]])

In [87]:
e_vec.transpose()[0][0]/np.sum(e_vec.transpose()[0])

0.5454545454545454